import './page-scroll';
import './article-scroll';
import './dialog-scroll';
import './map';
import './navigation';
import './goods-list';
import './goods';
import './dialog';
import './basket-button';
import './order-form';
import './feedback-form';
import './articles-list'
import './video-link'
import './article-link'
import './kettle-slider'
